<?php

/**
 * Zenbership Update
 *
 * @date 		2016-11-29
 * @link 		http://documentation.zenbership.com/Home/Updating-Zenbership
 * @version 	v108
 *
 * CHANGES
 * - Source Tracking with A/B testing options
 * - SMS Improvements
 * - E-Mail Improvements
 * - One click email reply on form submissions
 * - Invoices/subscription improvements:
 *   - Invoices spawned from subscriptions now credit the subscription when paid;
 *   - When not paid, it cancels the subscription;
 *   - If the subscription comes to renewal again but the invoice hasn't been paid, both are canceled.
 * - Event attendee improvements.
 * - New feed items and general improvements.
 * - Added better descriptions and help bubbles throughout the control panel.
 * - Criteria error logs added.
 * - Improved quick search.
 * - New hooks added, including subscription upgrade/downgrade and contact pipeline movement.
 * - Admin dashboard layout changes.
 * - Performance improvements.
 *
 * NEW PLUGINS
 * - Mailgun
 * - Sendgrid
 * - Mandrill
 * - Twilio
 * - Plivo
 * - Nexmo
 * - Sinch!
 * - Docusign
 * - MyBB
 * - E-Mailing Piping
 */ 

return array(
	"ALTER TABLE `ppSD_sources` ADD `trigger` VARCHAR(50) NULL;",
	"ALTER TABLE `ppSD_sources` ADD `redirect` VARCHAR(200) NULL;",
	"ALTER TABLE `ppSD_sources` ADD `redirect_b` VARCHAR(200) NULL;",
	"CREATE TABLE `ppSD_source_tracking` (`id` int(11) unsigned NOT NULL AUTO_INCREMENT, `source_id` int(11) DEFAULT NULL, `date` datetime DEFAULT NULL, `referrer` varchar(255) DEFAULT NULL, `ip` varchar(20) DEFAULT NULL, `converted` tinyint(1) DEFAULT NULL, `converted_date` datetime DEFAULT NULL, `user_id` varchar(50) DEFAULT NULL, `user_type` enum('member','contact','rsvp') DEFAULT NULL, PRIMARY KEY (`id`), KEY `source_id` (`source_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;",
	"CREATE TABLE `ppSD_source_tracking` (`id` int(11) unsigned NOT NULL AUTO_INCREMENT, `source_id` int(11) DEFAULT NULL, `date` datetime DEFAULT NULL, `referrer` varchar(255) DEFAULT NULL, `ip` varchar(20) DEFAULT NULL, `converted` tinyint(1) DEFAULT '0', `converted_date` datetime DEFAULT NULL, `user_id` varchar(50) DEFAULT NULL, `user_type` enum('member','contact','rsvp') DEFAULT NULL, `link_variation` enum('-','A','B') DEFAULT NULL, PRIMARY KEY (`id`), KEY `source_id` (`source_id`)) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;",
	"ALTER TABLE `ppSD_invoices` ADD `quote` TINYINT(1);",
	"ALTER TABLE `ppSD_invoices` ADD `quote_id` VARCHAR(30);",
	"UPDATE ppSD_data_eav SET `value`='date,last_name,first_name,status,type,arrived,arrived_date,order_id,purchased' WHERE `key`='rsvp_print' LIMIT 1;",
	"INSERT INTO `ppSD_options` (`id` ,`display` ,`value` ,`description` ,`type` ,`width` ,`options` ,`section` ,`maxlength` , `class` ) VALUES ('sms_plugin',  'SMS Plugin',  '', 'Enter the plugin ID you want to use for SMS sending.',  'text',  '15',  '', 'sms',  '',  '');",
	"INSERT INTO `ppSD_options` (`id` ,`display` ,`value` ,`description` ,`type` ,`width` ,`options` ,`section` ,`maxlength` , `class` ) VALUES ('email_plugin',  'E-Mail Plugin',  '', 'Enter the plugin ID you want to use for SMS sending.',  'text',  '150',  '', 'email',  '',  '');",
	"ALTER TABLE `ppSD_saved_sms` ADD `cell` VARCHAR(30) NULL;",
	"ALTER TABLE `ppSD_saved_sms` ADD `carrier` VARCHAR(30) NULL;",
	"ALTER TABLE `ppSD_saved_sms` ADD `sentvia` VARCHAR(30) NULL;",
	"ALTER TABLE `ppSD_saved_sms` ADD `media` VARCHAR(255) NULL;",
	"ALTER TABLE `ppSD_saved_sms` ADD `provider_id` VARCHAR(50) NULL;",
	"ALTER TABLE `ppSD_saved_sms` ADD `success` TINYINT(1) NULL;",
	"ALTER TABLE `ppSD_saved_sms` ADD `code` VARCHAR(10) NULL;",
	"ALTER TABLE `ppSD_saved_sms` ADD `message` VARCHAR(50) NULL;",
	"ALTER TABLE `ppSD_saved_emails` ADD `sentvia` VARCHAR(30) NULL;",
	"ALTER TABLE `ppSD_saved_emails` ADD `vendor_id` VARCHAR(100) NULL;",
	"ALTER TABLE `ppSD_custom_actions` ADD `plugin` VARCHAR(50) NULL;",
	"ALTER TABLE `ppSD_uploads` CHANGE `filename` `filename` VARCHAR(150) NULL;",
	"ALTER TABLE `ppSD_history` ADD `plugin` VARCHAR(30) NULL;",
	"ALTER TABLE `ppSD_custom_actions` ADD `order` INT(6) NULL;",
	"UPDATE ppSD_custom_actions SET `order`='0' WHERE `order` IS NULL;",
	"DELETE FROM ppSD_fieldsets WHERE `id`='300' AND `static`='1';",
	"UPDATE ppSD_fieldset_locations SET `fieldset_id`='22' WHERE `fieldset_id`='300';",
	"UPDATE ppSD_fieldsets_fields SET `fieldset`='22' WHERE `fieldset`='300';",
	"INSERT INTO `ppSD_activity_methods` (`id`, `icon`, `link`, `link_type`, `custom`, `text`, `in_feed`) VALUES ('form_submit', 'icon-new.png', 'contact-view', 'slider', 0, 'Form submitted by %act%.', 0);",
	"INSERT INTO `ppSD_activity_methods` (`id`, `icon`, `link`, `link_type`, `text`, `in_feed`, `custom`) VALUES ('event_checkin', 'icon-checkin.png', 'rsvp_view', 'popup', '%act% has checked in.', 1, 0);",
	"ALTER TABLE `ppSD_invoices` ADD `sub_id` VARCHAR(30) NULL;",
	"ALTER TABLE `ppSD_subscriptions` ADD `spawned_invoice` VARCHAR(35) NULL;",
	"UPDATE ppSD_activity_methods SET `link`='member-view',`link_type`='slider',`text`='SMS sent to %act%.',`in_feed`='1' WHERE `id`='sms' LIMIT 1;",
	"ALTER TABLE `ppSD_activity_methods` CHANGE `link_type` `link_type` VARCHAR(13) NULL;",
	"UPDATE `ppSD_activity_methods` SET `icon`='icon-warning.png' WHERE `id`='subscription_failed' LIMIT 1;",
	"UPDATE `ppSD_activity_methods` SET `icon`='icon-email-sent.png' WHERE `id`='email' LIMIT 1;",
	"UPDATE `ppSD_activity_methods` SET `icon`='icon-sub-failed.png' WHERE `id`='subscription_failed' LIMIT 1;",
	"UPDATE `ppSD_activity_methods` SET `icon`='icon-edit-on.png' WHERE `id`='member_update' LIMIT 1;",
	"UPDATE `ppSD_activity_methods` SET `icon`='icon-edit-on.png' WHERE `id`='member_staff_update' LIMIT 1;",
	"UPDATE `ppSD_activity_methods` SET `icon`='icon-email-read.png' WHERE `id`='read_email' LIMIT 1;",
	"UPDATE `ppSD_activity_methods` SET `icon`='icon-form-submitted.png' WHERE `id`='form_submit' LIMIT 1;",
	"UPDATE `ppSD_activity_methods` SET `icon`='icon-mail-bounced.png' WHERE `id`='bounced' LIMIT 1;",
	"INSERT INTO `ppSD_activity_methods` (`id`, `icon`, `link`, `link_type`, `text`, `in_feed`, `custom`) VALUES ('error', 'icon-system-error.png', 'system_alerts', 'alert', '', 1, 0);",
	"INSERT INTO `ppSD_options` (`id`, `display`, `value`, `description`, `type`, `width`, `options`, `section`, `maxlength`, `class`) VALUES ('cron_alerts', '', '0', '', '', '0', '', 'system', '0', '');",
	"INSERT INTO `ppSD_activity_methods` (`id`, `icon`, `link`, `link_type`, `text`, `in_feed`, `custom`) VALUES ('subscription_upgrade', 'icon-subscriptions-upgrade.png', 'subscription-view', 'slider', 'Subscription No. %act% upgraded.', '1', '');",
	"INSERT INTO `ppSD_activity_methods` (`id`, `icon`, `link`, `link_type`, `text`, `in_feed`, `custom`) VALUES ('subscription_downgrade', 'icon-subscriptions-downgrade.png', 'subscription-view', 'slider', 'Subscription No. %act% downgraded.', '1', '');",
	"UPDATE ppSD_options SET `value`='LnnnnnnnnnnnLLLnnnn' WHERE `id`='sub_id_format' LIMIT 1;",
	"ALTER TABLE `ppSD_notes` ADD `seen` TINYINT(1) default '0';",
	"ALTER TABLE `ppSD_notes` ADD `seen_date` DATETIME;",
	"ALTER TABLE `ppSD_history` CHANGE `method` `method` VARCHAR(75);",
	"INSERT INTO `ppSD_options` (`id`, `display`, `value`, `description`, `type`, `width`, `options`, `section`, `maxlength`, `class`) VALUES ('welcome_guide', '', '0', '', '', '0', '', 'system', '0', '');",
	"ALTER TABLE `ppSD_invoices` ADD `rolling_invoice` TINYINT(1) NULL;",
	"ALTER TABLE `ppSD_note_labels` ADD `static_lookup` VARCHAR(10) NULL;",
	"INSERT INTO `ppSD_note_labels` (`label`, `color`, `static_lookup`) VALUES ('E-Mail Received', 'CCC', 'emailin');",
	"UPDATE `ppSD_note_labels` SET `static_lookup`='important' WHERE `label`='Important' LIMIT 1;",
	"UPDATE `ppSD_note_labels` SET `static_lookup`='emailin' WHERE `label`='E-Mail Received' LIMIT 1;",
	"UPDATE `ppSD_note_labels` SET `static_lookup`='emailout' WHERE `label`='E-Mail Sent' LIMIT 1;",
	"UPDATE `ppSD_note_labels` SET `static_lookup`='appointment' WHERE `label`='Appointment' LIMIT 1;",
	"UPDATE `ppSD_note_labels` SET `static_lookup`='todo' WHERE `label`='To Do' LIMIT 1;",
	"UPDATE `ppSD_note_labels` SET `static_lookup`='misc' WHERE `label`='Miscellaneous' LIMIT 1;",
	"INSERT INTO `ppSD_options` (`id`, `display`, `value`, `description`, `type`, `width`, `options`, `section`, `maxlength`, `class`) VALUES ('cc_expiring_notify', 'Notify Expiring Credit Cards?', '1', 'If set to yes, users will be notified of upcoming expiring credit cards one month before they expire.', 'radio', '0', '', 'cart', '0', '');",
	"ALTER TABLE `ppSD_cart_billing` ADD `notice_sent` TINYINT(1) NULL;",
	"INSERT INTO `ppSD_templates_email` (`template`, `title`, `desc`, `subject`, `to`, `from`, `cc`, `bcc`, `content`, `format`, `status`, `save`, `track`, `track_links`, `caller_tags`, `custom`, `owner`, `public`, `created`, `header_id`, `footer_id`, `static`, `default_for`, `theme`, `type`) VALUES
	('cart_credit_card_expiring', 'Credit Card Expiring', 'Credit card is expiring soon.', 'Your credit card is expiring soon!', '', '', '', '', '', 1, 1, 1, 0, 0, '', 0, 2, 0, '" . $date . "', '', '', 1, 0, 'threefiveten', 'template');",
	"ALTER TABLE `ppSD_cart_billing` CHANGE `id` `id` VARCHAR(20) NULL;",
	"ALTER TABLE `ppSD_accounts` CHANGE `created` `created` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_accounts` CHANGE `last_updated` `last_updated` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_accounts` CHANGE `last_action` `last_action` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_bounced_emails` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cache` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cache` CHANGE `expires` `expires` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_calendars` CHANGE `created` `created` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_campaigns` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_campaigns` CHANGE `last_sent` `last_sent` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_campaign_items` CHANGE `when_date` `when_date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_campaign_logs` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_campaign_subscriptions` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_campaign_subscriptions` CHANGE `optin_date` `optin_date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_campaign_unsubscribe` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cart_categories` CHANGE `created` `created` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cart_coupon_codes` CHANGE `date_start` `date_start` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cart_coupon_codes` CHANGE `date_end` `date_end` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cart_coupon_codes` CHANGE `created` `created` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cart_coupon_codes_used` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cart_items` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cart_items_complete` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cart_refunds` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cart_sessions` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cart_sessions` CHANGE `date_completed` `date_completed` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cart_sessions` CHANGE `last_activity` `last_activity` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cart_sessions` CHANGE `return_time_out` `return_time_out` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cart_terms` CHANGE `created` `created` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_cart_tracking` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_contacts` CHANGE `created` `created` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_contacts` CHANGE `bounce_notice` `bounce_notice` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_contacts` CHANGE `last_updated` `last_updated` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_contacts` CHANGE `last_action` `last_action` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_contacts` CHANGE `next_action` `next_action` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_contacts` CHANGE `email_optout` `email_optout` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_contacts` CHANGE `sms_output` `sms_output` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_contact_data` CHANGE `dob` `dob` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_content_access` CHANGE `added` `added` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_content_access` CHANGE `expires` `expires` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_criteria_cache` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_custom_actions` CHANGE `created` `created` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_email_scheduled` CHANGE `added` `added` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_email_trackback` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_email_trackback` CHANGE `viewed` `viewed` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_email_trackback` CHANGE `last_viewed` `last_viewed` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_events` CHANGE `starts` `starts` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_events` CHANGE `ends` `ends` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_events` CHANGE `start_registrations` `start_registrations` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_events` CHANGE `early_bird_end` `early_bird_end` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_events` CHANGE `close_registration` `close_registration` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_events` CHANGE `created` `created` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_event_reminder_logs` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_event_rsvps` CHANGE `arrived_date` `arrived_date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_event_rsvps` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_event_rsvps` CHANGE `bounce_notice` `bounce_notice` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_event_timeline` CHANGE `starts` `starts` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_event_timeline` CHANGE `ends` `ends` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_favorites` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_forms` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_form_closed_sessions` CHANGE `date_issued` `date_issued` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_form_closed_sessions` CHANGE `date_used` `date_used` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_form_submit` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_form_requests` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_form_requests` CHANGE `expires` `expires` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_form_requests` CHANGE `completed` `completed` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_form_sessions` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_form_sessions` CHANGE `last_activity` `last_activity` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_history` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_invoices` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_invoices` CHANGE `last_reminder` `last_reminder` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_invoices` CHANGE `date_due` `date_due` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_invoice_components` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_invoice_payments` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_lead_conversion` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_lead_conversion` CHANGE `began` `began` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_link_tracking` CHANGE `first_clicked` `first_clicked` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_link_tracking` CHANGE `last_clicked` `last_clicked` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_logins` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_login_announcements` CHANGE `starts` `starts` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_login_announcements` CHANGE `ends` `ends` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_login_announcement_logs` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_members` CHANGE `bounce_notice` `bounce_notice` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_members` CHANGE `joined` `joined` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_members` CHANGE `last_renewal` `last_renewal` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_members` CHANGE `last_action` `last_action` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_members` CHANGE `last_login` `last_login` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_members` CHANGE `last_updated` `last_updated` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_members` CHANGE `next_action` `next_action` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_members` CHANGE `concurrent_login_date` `concurrent_login_date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_members` CHANGE `locked` `locked` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_members` CHANGE `email_output` `email_output` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_members` CHANGE `sms_optout` `sms_optout` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_members` CHANGE `activated` `activated` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_newsletters_subscribers` CHANGE `added` `added` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_newsletters_subscribers` CHANGE `expires` `expires` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_newsletters_subscribers` CHANGE `unsubscribed` `unsubscribed` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_newsletters_subscribers` CHANGE `double_optin` `double_optin` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_notes` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_notes` CHANGE `deadline` `deadline` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_notes` CHANGE `completed_on` `completed_on` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_notes` CHANGE `seen_date` `seen_date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_products` CHANGE `threshold_date_set` `threshold_date_set` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_products` CHANGE `created` `created` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_reset_passwords` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_saved_emails` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_saved_sms` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_schedule_social` CHANGE `post_date` `post_date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_saved_email_content` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_sessions` CHANGE `created` `created` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_sessions` CHANGE `ended` `ended` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_sessions` CHANGE `last_activity` `last_activity` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_shipping` CHANGE `ship_date` `ship_date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_shipping_rules` CHANGE `created` `created` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_social_media_feed` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_staff` CHANGE `locked` `locked` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_staff` CHANGE `created` `created` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_staff` CHANGE `last_updated` `last_updated` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_staff_in` CHANGE `masterlog` `masterlog` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_staff_in` CHANGE `expires` `expires` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_staff_in` CHANGE `complete` `complete` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_subscriptions` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_subscriptions` CHANGE `last_renewed` `last_renewed` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_subscriptions` CHANGE `next_renew` `next_renew` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_subscriptions` CHANGE `next_renew_keep` `next_renew_keep` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_subscriptions` CHANGE `cancel_date` `cancel_date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_tax_classes` CHANGE `created` `created` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_templates_lang` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_templates_email` CHANGE `created` `created` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_tracking_activity` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_trash_bin` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_uploads` CHANGE `date` `date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_usage_logs` CHANGE `start_date` `start_date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_usage_logs` CHANGE `end_date` `end_date` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE `ppSD_widgets` CHANGE `installed` `installed` datetime DEFAULT '0000-00-00 00:00:00';",
	"ALTER TABLE  `ppSD_usage_logs` CHANGE  `success`  `success` TINYINT( 1 ) NOT NULL DEFAULT  '1';",
	"ALTER TABLE  `ppSD_usage_logs` CHANGE  `msg`  `msg` VARCHAR( 255 ) NULL;",
	"CREATE TABLE `ppSD_donations` (`id` int(11) unsigned NOT NULL AUTO_INCREMENT,  `date` datetime DEFAULT NULL,  `member_id` varchar(20) DEFAULT NULL,  `member_type` enum('member','contact') DEFAULT NULL,  `product_id` int(11) DEFAULT NULL,  `total` decimal(10,2) DEFAULT NULL,  `public` tinyint(1) DEFAULT NULL,  `comments` mediumtext,  PRIMARY KEY (`id`),  KEY `product_id` (`product_id`),  KEY `member_id` (`member_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;",
	"CREATE TABLE `ppSD_donation_campaigns` (`id` int(11) unsigned NOT NULL AUTO_INCREMENT, `starts` datetime DEFAULT NULL, `ends` datetime DEFAULT NULL, `goal` decimal(10,2) DEFAULT NULL, `name` varchar(50) DEFAULT NULL, `description` mediumtext, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;",
	"CREATE TABLE `ppSD_donation_amounts` (`id` int(11) unsigned NOT NULL AUTO_INCREMENT, `campaign_id` int(11) DEFAULT NULL, `name` varchar(60) DEFAULT NULL, `description` mediumtext, `amount` decimal(10,2) DEFAULT NULL, PRIMARY KEY (`id`), KEY `campaign_id` (`campaign_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;",
	"ALTER TABLE `ppSD_cart_sessions` ADD `donation` TINYINT(1) NULL;",
	"INSERT INTO `ppSD_templates` (`id`, `path`, `theme`, `subtemplate`, `title`, `desc`, `caller_tags`, `order`, `custom_header`, `custom_footer`, `custom_template`, `type`, `section`, `content`, `secure`, `static`, `owner`, `encrypt`, `meta_title`, `lang`) VALUES ('donate', '', 'zoid', '', 'Donation Page', '', '', 0, '0', '0', '', 0, 'Cart', '', 0, 1, 2, 0, '', 'en');",
	"INSERT INTO `ppSD_templates` (`id`, `path`, `theme`, `subtemplate`, `title`, `desc`, `caller_tags`, `order`, `custom_header`, `custom_footer`, `custom_template`, `type`, `section`, `content`, `secure`, `static`, `owner`, `encrypt`, `meta_title`, `lang`) VALUES ('donate_product_entry', '', 'zoid', '', 'Donation Page: Product Entry', '', '', 0, '0', '0', '', 0, 'Cart', '', 0, 1, 2, 0, '', 'en');",
	"INSERT INTO `ppSD_templates` (`id`, `path`, `theme`, `subtemplate`, `title`, `desc`, `caller_tags`, `order`, `custom_header`, `custom_footer`, `custom_template`, `type`, `section`, `content`, `secure`, `static`, `owner`, `encrypt`, `meta_title`, `lang`) VALUES ('donate_campaigns', '', 'zoid', '', 'Donation Campaign Listing Page', '', '', 0, '0', '0', '', 0, 'Cart', '', 0, 1, 2, 0, '', 'en');",
	"INSERT INTO `ppSD_templates` (`id`, `path`, `theme`, `subtemplate`, `title`, `desc`, `caller_tags`, `order`, `custom_header`, `custom_footer`, `custom_template`, `type`, `section`, `content`, `secure`, `static`, `owner`, `encrypt`, `meta_title`, `lang`) VALUES ('donate_campaign_entry', '', 'zoid', '', 'Donation Campaign Listing Page: Entry', '', '', 0, '0', '0', '', 0, 'Cart', '', 0, 1, 2, 0, '', 'en');",
	"INSERT INTO `ppSD_templates_email` (`template`, `title`, `desc`, `subject`, `to`, `from`, `cc`, `bcc`, `content`, `format`, `status`, `save`, `track`, `track_links`, `caller_tags`, `custom`, `owner`, `public`, `created`, `header_id`, `footer_id`, `static`, `default_for`, `theme`, `type`) VALUES ('donation_thankyou', 'Donation Thank You', '', 'Thank you for your donation!', '', '', '', '', '', 1, 1, 0, 0, 0, '', 0, 2, 0, '0000-00-00 00:00:00', '', '', 1, 0, 'threefiveten', 'template');",
	"UPDATE `ppSD_forms` SET  `act_id` =  '' WHERE  `act_id` IS NULL;",
	"ALTER TABLE  `ppSD_forms` CHANGE  `act_id`  `act_id` VARCHAR( 20 ) NOT NULL DEFAULT  '';",
);
